// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_TVALID,
        dst_TREADY,
        width,
        mul_ln112,
        src_TDATA,
        src_TREADY,
        src_TKEEP,
        src_TSTRB,
        src_TUSER,
        src_TLAST,
        src_TID,
        src_TDEST,
        threshold_val,
        icmp_ln180,
        icmp_ln180_1,
        icmp_ln180_2,
        icmp_ln180_3,
        icmp_ln180_4,
        sub_i_i,
        dst_TDATA,
        dst_TVALID,
        dst_TKEEP,
        dst_TSTRB,
        dst_TUSER,
        dst_TLAST,
        dst_TID,
        dst_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   src_TVALID;
input   dst_TREADY;
input  [15:0] width;
input  [31:0] mul_ln112;
input  [7:0] src_TDATA;
output   src_TREADY;
input  [0:0] src_TKEEP;
input  [0:0] src_TSTRB;
input  [0:0] src_TUSER;
input  [0:0] src_TLAST;
input  [0:0] src_TID;
input  [0:0] src_TDEST;
input  [7:0] threshold_val;
input  [0:0] icmp_ln180;
input  [0:0] icmp_ln180_1;
input  [0:0] icmp_ln180_2;
input  [0:0] icmp_ln180_3;
input  [0:0] icmp_ln180_4;
input  [16:0] sub_i_i;
output  [7:0] dst_TDATA;
output   dst_TVALID;
output  [0:0] dst_TKEEP;
output  [0:0] dst_TSTRB;
output  [0:0] dst_TUSER;
output  [0:0] dst_TLAST;
output  [0:0] dst_TID;
output  [0:0] dst_TDEST;

reg ap_idle;
reg src_TREADY;
reg dst_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln1027_1_fu_348_p2;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln1027_1_reg_1189;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0;
reg    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0;
wire   [9:0] image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_address1;
reg    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1;
wire   [7:0] image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1;
wire   [9:0] image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_address0;
reg    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0;
reg    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0;
wire   [7:0] image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0;
reg    src_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    dst_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln180_1_read_reg_1164;
reg   [7:0] tmp_data_V_1_reg_1193;
reg   [0:0] tmp_keep_V_reg_1203;
reg   [0:0] tmp_strb_V_reg_1208;
reg   [0:0] tmp_user_V_reg_1213;
reg   [0:0] tmp_id_V_reg_1218;
reg   [0:0] tmp_dest_V_reg_1223;
reg   [9:0] image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_line_buffer_1_addr_reg_1228;
wire   [0:0] valid_window_fu_471_p2;
reg   [0:0] valid_window_reg_1239;
wire   [0:0] icmp_ln1035_fu_477_p2;
reg   [0:0] icmp_ln1035_reg_1247;
wire   [0:0] dst_pixel_last_V_fu_486_p2;
reg   [0:0] dst_pixel_last_V_reg_1252;
wire   [63:0] zext_ln1027_fu_424_p1;
reg   [7:0] sum_V_1_fu_154;
reg   [7:0] p_0_0_0357_1841_fu_158;
reg   [7:0] p_0_0_0357_2843_fu_162;
reg   [9:0] col_fu_166;
wire   [9:0] add_ln148_fu_491_p2;
wire    ap_loop_init;
reg   [15:0] row_fu_170;
wire   [15:0] select_ln1027_1_fu_416_p3;
reg   [31:0] indvar_flatten_fu_174;
wire   [31:0] add_ln1027_fu_353_p2;
reg   [7:0] p_0_0_0356840_fu_178;
reg   [7:0] p_0_0_0356_1842_fu_182;
reg   [7:0] current_pixel_V_fu_186;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] zext_ln1027_1_fu_339_p1;
wire   [0:0] icmp_ln1027_fu_343_p2;
wire   [15:0] add_ln144_fu_370_p2;
wire   [14:0] tmp_2_fu_376_p4;
wire   [14:0] tmp_3_fu_392_p4;
wire   [0:0] icmp_fu_386_p2;
wire   [0:0] icmp55_fu_402_p2;
wire   [9:0] select_ln144_fu_362_p3;
wire   [8:0] tmp_4_fu_455_p4;
wire   [0:0] select_ln144_1_fu_408_p3;
wire   [0:0] icmp_ln178_fu_465_p2;
wire   [16:0] zext_ln1019_fu_482_p1;
wire   [9:0] shl_ln_fu_554_p3;
wire   [10:0] zext_ln840_4_fu_566_p1;
wire   [10:0] zext_ln840_2_fu_550_p1;
wire   [10:0] add_ln840_fu_570_p2;
wire   [8:0] zext_ln840_1_fu_546_p1;
wire   [8:0] zext_ln840_5_fu_584_p1;
wire   [8:0] add_ln840_1_fu_588_p2;
wire   [11:0] zext_ln88_fu_576_p1;
wire   [11:0] zext_ln840_6_fu_594_p1;
wire   [11:0] sum_V_5_fu_598_p2;
wire   [11:0] zext_ln840_fu_542_p1;
wire   [11:0] sum_V_6_fu_604_p2;
wire   [11:0] zext_ln88_1_fu_580_p1;
wire   [11:0] sum_V_fu_610_p2;
wire   [8:0] zext_ln28_fu_644_p1;
wire   [8:0] tmp8_fu_656_p2;
wire   [9:0] tmp_fu_662_p3;
wire   [8:0] zext_ln840_7_fu_632_p1;
wire   [8:0] tmp11_fu_674_p2;
wire   [9:0] tmp_1_fu_680_p3;
wire   [8:0] p_0_0_0357839_cast_fu_628_p1;
wire   [8:0] p_0_0_0357_2843_cast_fu_652_p1;
wire   [8:0] add_ln840_2_fu_701_p2;
wire   [9:0] zext_ln840_10_fu_698_p1;
wire   [9:0] zext_ln840_11_fu_707_p1;
wire   [9:0] gx_V_2_fu_711_p2;
wire  signed [10:0] tmp_cast_fu_670_p1;
wire   [10:0] zext_ln29_1_fu_636_p1;
wire   [10:0] add_ln840_3_fu_721_p2;
wire  signed [10:0] sext_ln840_fu_717_p1;
wire   [8:0] gy_V_3_fu_733_p2;
wire  signed [10:0] sext_ln29_fu_688_p1;
wire   [10:0] zext_ln840_8_fu_692_p1;
wire   [10:0] add_ln840_5_fu_743_p2;
wire  signed [10:0] sext_ln840_1_fu_739_p1;
wire   [10:0] gy_V_4_fu_749_p2;
wire   [10:0] gx_V_fu_727_p2;
wire   [0:0] tmp_6_fu_761_p3;
wire   [10:0] abs_gx_V_fu_769_p2;
wire  signed [10:0] abs_gx_V_1_fu_775_p3;
wire   [10:0] gy_V_fu_755_p2;
wire   [0:0] tmp_7_fu_787_p3;
wire   [10:0] abs_gy_V_fu_795_p2;
wire  signed [10:0] abs_gy_V_1_fu_801_p3;
wire  signed [11:0] sext_ln43_fu_783_p1;
wire  signed [11:0] sext_ln44_fu_809_p1;
wire   [11:0] magnitude_V_fu_821_p2;
wire   [3:0] tmp_8_fu_827_p4;
wire   [7:0] trunc_ln45_1_fu_817_p1;
wire   [7:0] trunc_ln45_fu_813_p1;
wire   [0:0] icmp_ln1035_1_fu_837_p2;
wire   [7:0] add_ln186_fu_843_p2;
wire   [8:0] tmp25_fu_861_p2;
wire   [9:0] tmp25_cast_fu_867_p1;
wire   [9:0] tmp24_cast_fu_857_p1;
wire   [9:0] tmp66_fu_871_p2;
wire   [10:0] tmp7_fu_877_p3;
wire   [11:0] zext_ln840_12_fu_885_p1;
wire   [11:0] p_0_0_0357_2843_cast36_fu_648_p1;
wire   [11:0] add_ln840_7_fu_889_p2;
wire   [11:0] zext_ln840_3_fu_562_p1;
wire   [8:0] zext_ln840_9_fu_695_p1;
wire   [8:0] zext_ln29_fu_640_p1;
wire   [8:0] add_ln840_9_fu_901_p2;
wire   [9:0] zext_ln840_13_fu_907_p1;
wire   [9:0] p_0_0_0357839_cast39_fu_624_p1;
wire   [9:0] add_ln840_10_fu_911_p2;
wire   [11:0] zext_ln840_14_fu_917_p1;
wire   [11:0] add_ln840_8_fu_895_p2;
wire   [11:0] sum_V_4_fu_921_p2;
wire   [3:0] tmp_9_fu_937_p4;
wire   [0:0] icmp_ln1035_2_fu_947_p2;
wire   [7:0] trunc_ln186_fu_953_p1;
wire   [7:0] xor_ln186_fu_530_p2;
wire   [7:0] select_ln214_fu_535_p3;
wire   [7:0] select_ln180_fu_965_p3;
wire   [0:0] tmp_5_fu_616_p3;
wire   [0:0] and_ln178_fu_978_p2;
wire   [0:0] xor_ln1027_fu_982_p2;
wire   [0:0] and_ln1027_fu_988_p2;
wire   [7:0] output_pixel_1_fu_957_p3;
wire   [7:0] select_ln180_1_fu_971_p3;
wire   [0:0] and_ln178_1_fu_1002_p2;
wire   [7:0] trunc_ln1_fu_927_p4;
wire   [7:0] select_ln1027_fu_994_p3;
wire   [0:0] and_ln180_fu_1014_p2;
wire   [7:0] output_pixel_fu_849_p3;
wire   [7:0] select_ln178_fu_1006_p3;
wire   [0:0] xor_ln178_fu_1026_p2;
wire   [0:0] and_ln180_1_fu_1031_p2;
wire   [0:0] and_ln1027_1_fu_1036_p2;
wire   [0:0] or_ln1027_fu_1042_p2;
wire   [7:0] select_ln180_2_fu_1018_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP_image_pros_stream_stream_ap_uint_ap_uinbkb #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_line_buffer_1_addr_reg_1228),
    .ce0(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0),
    .we0(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0),
    .d0(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0),
    .address1(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_address1),
    .ce1(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1),
    .q1(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1)
);

image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP_image_pros_stream_stream_ap_uint_ap_uincud #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_address0),
    .ce0(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0),
    .we0(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0),
    .d0(src_TDATA),
    .q0(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0)
);

image_pros_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            col_fu_166 <= 10'd0;
        end else if (((icmp_ln1027_1_fu_348_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            col_fu_166 <= add_ln148_fu_491_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_174 <= 32'd0;
        end else if (((icmp_ln1027_1_fu_348_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_174 <= add_ln1027_fu_353_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            row_fu_170 <= 16'd0;
        end else if (((icmp_ln1027_1_fu_348_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            row_fu_170 <= select_ln1027_1_fu_416_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_1_reg_1189 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        current_pixel_V_fu_186 <= tmp_data_V_1_reg_1193;
        p_0_0_0356840_fu_178 <= image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1;
        p_0_0_0356_1842_fu_182 <= image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0;
        p_0_0_0357_1841_fu_158 <= p_0_0_0356_1842_fu_182;
        p_0_0_0357_2843_fu_162 <= current_pixel_V_fu_186;
        sum_V_1_fu_154 <= p_0_0_0356840_fu_178;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_1_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_pixel_last_V_reg_1252 <= dst_pixel_last_V_fu_486_p2;
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_line_buffer_1_addr_reg_1228 <= zext_ln1027_fu_424_p1;
        tmp_data_V_1_reg_1193 <= src_TDATA;
        tmp_dest_V_reg_1223 <= src_TDEST;
        tmp_id_V_reg_1218 <= src_TID;
        tmp_keep_V_reg_1203 <= src_TKEEP;
        tmp_strb_V_reg_1208 <= src_TSTRB;
        tmp_user_V_reg_1213 <= src_TUSER;
        valid_window_reg_1239 <= valid_window_fu_471_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1027_1_reg_1189 <= icmp_ln1027_1_fu_348_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_1_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln180_1_read_reg_1164 == 1'd1))) begin
        icmp_ln1035_reg_1247 <= icmp_ln1035_fu_477_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln1027_1_fu_348_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln1027_1_reg_1189 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dst_TDATA_blk_n = dst_TREADY;
    end else begin
        dst_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_1_reg_1189 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dst_TVALID = 1'b1;
    end else begin
        dst_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0 = 1'b1;
    end else begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1 = 1'b1;
    end else begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_1_reg_1189 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0 = 1'b1;
    end else begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_1_fu_348_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0 = 1'b1;
    end else begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_1_fu_348_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0 = 1'b1;
    end else begin
        image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln1027_1_fu_348_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_TDATA_blk_n = src_TVALID;
    end else begin
        src_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_1_fu_348_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_TREADY = 1'b1;
    end else begin
        src_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_gx_V_1_fu_775_p3 = ((tmp_6_fu_761_p3[0:0] == 1'b1) ? abs_gx_V_fu_769_p2 : gx_V_fu_727_p2);

assign abs_gx_V_fu_769_p2 = (11'd0 - gx_V_fu_727_p2);

assign abs_gy_V_1_fu_801_p3 = ((tmp_7_fu_787_p3[0:0] == 1'b1) ? abs_gy_V_fu_795_p2 : gy_V_fu_755_p2);

assign abs_gy_V_fu_795_p2 = (11'd0 - gy_V_fu_755_p2);

assign add_ln1027_fu_353_p2 = (indvar_flatten_fu_174 + 32'd1);

assign add_ln144_fu_370_p2 = (row_fu_170 + 16'd1);

assign add_ln148_fu_491_p2 = (select_ln144_fu_362_p3 + 10'd1);

assign add_ln186_fu_843_p2 = (trunc_ln45_1_fu_817_p1 + trunc_ln45_fu_813_p1);

assign add_ln840_10_fu_911_p2 = (zext_ln840_13_fu_907_p1 + p_0_0_0357839_cast39_fu_624_p1);

assign add_ln840_1_fu_588_p2 = (zext_ln840_1_fu_546_p1 + zext_ln840_5_fu_584_p1);

assign add_ln840_2_fu_701_p2 = (p_0_0_0357839_cast_fu_628_p1 + p_0_0_0357_2843_cast_fu_652_p1);

assign add_ln840_3_fu_721_p2 = ($signed(tmp_cast_fu_670_p1) + $signed(zext_ln29_1_fu_636_p1));

assign add_ln840_5_fu_743_p2 = ($signed(sext_ln29_fu_688_p1) + $signed(zext_ln840_8_fu_692_p1));

assign add_ln840_7_fu_889_p2 = (zext_ln840_12_fu_885_p1 + p_0_0_0357_2843_cast36_fu_648_p1);

assign add_ln840_8_fu_895_p2 = (add_ln840_7_fu_889_p2 + zext_ln840_3_fu_562_p1);

assign add_ln840_9_fu_901_p2 = (zext_ln840_9_fu_695_p1 + zext_ln29_fu_640_p1);

assign add_ln840_fu_570_p2 = (zext_ln840_4_fu_566_p1 + zext_ln840_2_fu_550_p1);

assign and_ln1027_1_fu_1036_p2 = (tmp_5_fu_616_p3 & and_ln178_fu_978_p2);

assign and_ln1027_fu_988_p2 = (xor_ln1027_fu_982_p2 & and_ln178_fu_978_p2);

assign and_ln178_1_fu_1002_p2 = (valid_window_reg_1239 & icmp_ln180_3);

assign and_ln178_fu_978_p2 = (valid_window_reg_1239 & icmp_ln180_2);

assign and_ln180_1_fu_1031_p2 = (xor_ln178_fu_1026_p2 & icmp_ln180_4);

assign and_ln180_fu_1014_p2 = (valid_window_reg_1239 & icmp_ln180_4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln1027_1_reg_1189 == 1'd0) & (dst_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln1027_1_fu_348_p2 == 1'd0) & (src_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln1027_1_reg_1189 == 1'd0) & (dst_TREADY == 1'b0)))) | ((icmp_ln1027_1_fu_348_p2 == 1'd0) & (src_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln1027_1_reg_1189 == 1'd0) & (dst_TREADY == 1'b0)))) | ((icmp_ln1027_1_fu_348_p2 == 1'd0) & (src_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln1027_1_fu_348_p2 == 1'd0) & (src_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln1027_1_reg_1189 == 1'd0) & (dst_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln1027_1_reg_1189 == 1'd0) & (dst_TREADY == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign dst_TDATA = ((or_ln1027_fu_1042_p2[0:0] == 1'b1) ? 8'd0 : select_ln180_2_fu_1018_p3);

assign dst_TDEST = tmp_dest_V_reg_1223;

assign dst_TID = tmp_id_V_reg_1218;

assign dst_TKEEP = tmp_keep_V_reg_1203;

assign dst_TLAST = dst_pixel_last_V_reg_1252;

assign dst_TSTRB = tmp_strb_V_reg_1208;

assign dst_TUSER = tmp_user_V_reg_1213;

assign dst_pixel_last_V_fu_486_p2 = ((sub_i_i == zext_ln1019_fu_482_p1) ? 1'b1 : 1'b0);

assign gx_V_2_fu_711_p2 = (zext_ln840_10_fu_698_p1 - zext_ln840_11_fu_707_p1);

assign gx_V_fu_727_p2 = ($signed(add_ln840_3_fu_721_p2) + $signed(sext_ln840_fu_717_p1));

assign gy_V_3_fu_733_p2 = (p_0_0_0357_2843_cast_fu_652_p1 - p_0_0_0357839_cast_fu_628_p1);

assign gy_V_4_fu_749_p2 = ($signed(add_ln840_5_fu_743_p2) + $signed(sext_ln840_1_fu_739_p1));

assign gy_V_fu_755_p2 = (gy_V_4_fu_749_p2 - zext_ln29_1_fu_636_p1);

assign icmp55_fu_402_p2 = ((tmp_3_fu_392_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_fu_386_p2 = ((tmp_2_fu_376_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln1027_1_fu_348_p2 = ((indvar_flatten_fu_174 == mul_ln112) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_343_p2 = ((zext_ln1027_1_fu_339_p1 == width) ? 1'b1 : 1'b0);

assign icmp_ln1035_1_fu_837_p2 = (($signed(tmp_8_fu_827_p4) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_947_p2 = (($signed(tmp_9_fu_937_p4) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_477_p2 = ((src_TDATA > threshold_val) ? 1'b1 : 1'b0);

assign icmp_ln178_fu_465_p2 = ((tmp_4_fu_455_p4 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_1_read_reg_1164 = icmp_ln180_1;

assign image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_address1 = zext_ln1027_fu_424_p1;

assign image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_address0 = zext_ln1027_fu_424_p1;

assign magnitude_V_fu_821_p2 = ($signed(sext_ln43_fu_783_p1) + $signed(sext_ln44_fu_809_p1));

assign or_ln1027_fu_1042_p2 = (and_ln180_1_fu_1031_p2 | and_ln1027_1_fu_1036_p2);

assign output_pixel_1_fu_957_p3 = ((icmp_ln1035_2_fu_947_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln186_fu_953_p1);

assign output_pixel_fu_849_p3 = ((icmp_ln1035_1_fu_837_p2[0:0] == 1'b1) ? 8'd255 : add_ln186_fu_843_p2);

assign p_0_0_0357839_cast39_fu_624_p1 = sum_V_1_fu_154;

assign p_0_0_0357839_cast_fu_628_p1 = sum_V_1_fu_154;

assign p_0_0_0357_2843_cast36_fu_648_p1 = p_0_0_0357_2843_fu_162;

assign p_0_0_0357_2843_cast_fu_652_p1 = p_0_0_0357_2843_fu_162;

assign select_ln1027_1_fu_416_p3 = ((icmp_ln1027_fu_343_p2[0:0] == 1'b1) ? add_ln144_fu_370_p2 : row_fu_170);

assign select_ln1027_fu_994_p3 = ((and_ln1027_fu_988_p2[0:0] == 1'b1) ? output_pixel_1_fu_957_p3 : select_ln180_1_fu_971_p3);

assign select_ln144_1_fu_408_p3 = ((icmp_ln1027_fu_343_p2[0:0] == 1'b1) ? icmp_fu_386_p2 : icmp55_fu_402_p2);

assign select_ln144_fu_362_p3 = ((icmp_ln1027_fu_343_p2[0:0] == 1'b1) ? 10'd0 : col_fu_166);

assign select_ln178_fu_1006_p3 = ((and_ln178_1_fu_1002_p2[0:0] == 1'b1) ? trunc_ln1_fu_927_p4 : select_ln1027_fu_994_p3);

assign select_ln180_1_fu_971_p3 = ((icmp_ln180_1[0:0] == 1'b1) ? select_ln214_fu_535_p3 : select_ln180_fu_965_p3);

assign select_ln180_2_fu_1018_p3 = ((and_ln180_fu_1014_p2[0:0] == 1'b1) ? output_pixel_fu_849_p3 : select_ln178_fu_1006_p3);

assign select_ln180_fu_965_p3 = ((icmp_ln180[0:0] == 1'b1) ? xor_ln186_fu_530_p2 : tmp_data_V_1_reg_1193);

assign select_ln214_fu_535_p3 = ((icmp_ln1035_reg_1247[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sext_ln29_fu_688_p1 = $signed(tmp_1_fu_680_p3);

assign sext_ln43_fu_783_p1 = abs_gx_V_1_fu_775_p3;

assign sext_ln44_fu_809_p1 = abs_gy_V_1_fu_801_p3;

assign sext_ln840_1_fu_739_p1 = $signed(gy_V_3_fu_733_p2);

assign sext_ln840_fu_717_p1 = $signed(gx_V_2_fu_711_p2);

assign shl_ln_fu_554_p3 = {{p_0_0_0356_1842_fu_182}, {2'd0}};

assign sum_V_4_fu_921_p2 = (zext_ln840_14_fu_917_p1 + add_ln840_8_fu_895_p2);

assign sum_V_5_fu_598_p2 = (zext_ln88_fu_576_p1 - zext_ln840_6_fu_594_p1);

assign sum_V_6_fu_604_p2 = (sum_V_5_fu_598_p2 - zext_ln840_fu_542_p1);

assign sum_V_fu_610_p2 = (sum_V_6_fu_604_p2 - zext_ln88_1_fu_580_p1);

assign tmp11_fu_674_p2 = (zext_ln840_5_fu_584_p1 - zext_ln840_7_fu_632_p1);

assign tmp24_cast_fu_857_p1 = add_ln840_1_fu_588_p2;

assign tmp25_cast_fu_867_p1 = tmp25_fu_861_p2;

assign tmp25_fu_861_p2 = (zext_ln840_7_fu_632_p1 + zext_ln28_fu_644_p1);

assign tmp66_fu_871_p2 = (tmp25_cast_fu_867_p1 + tmp24_cast_fu_857_p1);

assign tmp7_fu_877_p3 = {{tmp66_fu_871_p2}, {1'd0}};

assign tmp8_fu_656_p2 = (zext_ln28_fu_644_p1 - zext_ln840_1_fu_546_p1);

assign tmp_1_fu_680_p3 = {{tmp11_fu_674_p2}, {1'd0}};

assign tmp_2_fu_376_p4 = {{add_ln144_fu_370_p2[15:1]}};

assign tmp_3_fu_392_p4 = {{row_fu_170[15:1]}};

assign tmp_4_fu_455_p4 = {{select_ln144_fu_362_p3[9:1]}};

assign tmp_5_fu_616_p3 = sum_V_fu_610_p2[32'd11];

assign tmp_6_fu_761_p3 = gx_V_fu_727_p2[32'd10];

assign tmp_7_fu_787_p3 = gy_V_fu_755_p2[32'd10];

assign tmp_8_fu_827_p4 = {{magnitude_V_fu_821_p2[11:8]}};

assign tmp_9_fu_937_p4 = {{sum_V_fu_610_p2[11:8]}};

assign tmp_cast_fu_670_p1 = $signed(tmp_fu_662_p3);

assign tmp_fu_662_p3 = {{tmp8_fu_656_p2}, {1'd0}};

assign trunc_ln186_fu_953_p1 = sum_V_fu_610_p2[7:0];

assign trunc_ln1_fu_927_p4 = {{sum_V_4_fu_921_p2[11:4]}};

assign trunc_ln45_1_fu_817_p1 = abs_gx_V_1_fu_775_p3[7:0];

assign trunc_ln45_fu_813_p1 = abs_gy_V_1_fu_801_p3[7:0];

assign valid_window_fu_471_p2 = (select_ln144_1_fu_408_p3 & icmp_ln178_fu_465_p2);

assign xor_ln1027_fu_982_p2 = (tmp_5_fu_616_p3 ^ 1'd1);

assign xor_ln178_fu_1026_p2 = (valid_window_reg_1239 ^ 1'd1);

assign xor_ln186_fu_530_p2 = (tmp_data_V_1_reg_1193 ^ 8'd255);

assign zext_ln1019_fu_482_p1 = select_ln144_fu_362_p3;

assign zext_ln1027_1_fu_339_p1 = col_fu_166;

assign zext_ln1027_fu_424_p1 = select_ln144_fu_362_p3;

assign zext_ln28_fu_644_p1 = image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0;

assign zext_ln29_1_fu_636_p1 = image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1;

assign zext_ln29_fu_640_p1 = image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1;

assign zext_ln840_10_fu_698_p1 = tmp_data_V_1_reg_1193;

assign zext_ln840_11_fu_707_p1 = add_ln840_2_fu_701_p2;

assign zext_ln840_12_fu_885_p1 = tmp7_fu_877_p3;

assign zext_ln840_13_fu_907_p1 = add_ln840_9_fu_901_p2;

assign zext_ln840_14_fu_917_p1 = add_ln840_10_fu_911_p2;

assign zext_ln840_1_fu_546_p1 = p_0_0_0357_1841_fu_158;

assign zext_ln840_2_fu_550_p1 = p_0_0_0356_1842_fu_182;

assign zext_ln840_3_fu_562_p1 = shl_ln_fu_554_p3;

assign zext_ln840_4_fu_566_p1 = shl_ln_fu_554_p3;

assign zext_ln840_5_fu_584_p1 = current_pixel_V_fu_186;

assign zext_ln840_6_fu_594_p1 = add_ln840_1_fu_588_p2;

assign zext_ln840_7_fu_632_p1 = p_0_0_0356840_fu_178;

assign zext_ln840_8_fu_692_p1 = tmp_data_V_1_reg_1193;

assign zext_ln840_9_fu_695_p1 = tmp_data_V_1_reg_1193;

assign zext_ln840_fu_542_p1 = p_0_0_0356840_fu_178;

assign zext_ln88_1_fu_580_p1 = image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0;

assign zext_ln88_fu_576_p1 = add_ln840_fu_570_p2;

endmodule //image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP
