// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="image_pros_image_pros,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=16.693750,HLS_SYN_LAT=307208,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=329,HLS_SYN_LUT=976,HLS_VERSION=2022_2}" *)

module image_pros (
        ap_clk,
        ap_rst_n,
        src_TDATA,
        src_TVALID,
        src_TREADY,
        src_TKEEP,
        src_TSTRB,
        src_TUSER,
        src_TLAST,
        src_TID,
        src_TDEST,
        dst_TDATA,
        dst_TVALID,
        dst_TREADY,
        dst_TKEEP,
        dst_TSTRB,
        dst_TUSER,
        dst_TLAST,
        dst_TID,
        dst_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] src_TDATA;
input   src_TVALID;
output   src_TREADY;
input  [0:0] src_TKEEP;
input  [0:0] src_TSTRB;
input  [0:0] src_TUSER;
input  [0:0] src_TLAST;
input  [0:0] src_TID;
input  [0:0] src_TDEST;
output  [7:0] dst_TDATA;
output   dst_TVALID;
input   dst_TREADY;
output  [0:0] dst_TKEEP;
output  [0:0] dst_TSTRB;
output  [0:0] dst_TUSER;
output  [0:0] dst_TLAST;
output  [0:0] dst_TID;
output  [0:0] dst_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [2:0] filter_select;
wire   [7:0] threshold_val;
wire   [15:0] width;
wire   [15:0] height;
reg   [15:0] width_read_reg_226;
reg   [7:0] threshold_val_read_reg_232;
reg   [2:0] filter_select_read_reg_237;
wire   [16:0] sub_i_i_fu_182_p2;
reg   [16:0] sub_i_i_reg_256;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln180_fu_189_p2;
reg   [0:0] icmp_ln180_reg_261;
wire   [0:0] icmp_ln180_1_fu_195_p2;
reg   [0:0] icmp_ln180_1_reg_266;
wire   [0:0] icmp_ln180_2_fu_201_p2;
reg   [0:0] icmp_ln180_2_reg_271;
wire   [0:0] icmp_ln180_3_fu_207_p2;
reg   [0:0] icmp_ln180_3_reg_276;
wire   [0:0] icmp_ln180_4_fu_213_p2;
reg   [0:0] icmp_ln180_4_reg_281;
wire  signed [31:0] grp_fu_219_p2;
reg   [31:0] mul_ln112_reg_286;
wire    grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start;
wire    grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_done;
wire    grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_idle;
wire    grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_ready;
wire    grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TREADY;
wire    grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_src_TREADY;
wire   [7:0] grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TDATA;
wire    grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID;
wire   [0:0] grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TKEEP;
wire   [0:0] grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TSTRB;
wire   [0:0] grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TUSER;
wire   [0:0] grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TLAST;
wire   [0:0] grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TID;
wire   [0:0] grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TDEST;
reg    grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [16:0] width_cast_fu_179_p1;
wire   [15:0] grp_fu_219_p0;
wire   [15:0] grp_fu_219_p1;
wire    ap_CS_fsm_state6;
wire    regslice_both_dst_V_data_V_U_apdone_blk;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    regslice_both_src_V_data_V_U_apdone_blk;
wire   [7:0] src_TDATA_int_regslice;
wire    src_TVALID_int_regslice;
reg    src_TREADY_int_regslice;
wire    regslice_both_src_V_data_V_U_ack_in;
wire    regslice_both_src_V_keep_V_U_apdone_blk;
wire   [0:0] src_TKEEP_int_regslice;
wire    regslice_both_src_V_keep_V_U_vld_out;
wire    regslice_both_src_V_keep_V_U_ack_in;
wire    regslice_both_src_V_strb_V_U_apdone_blk;
wire   [0:0] src_TSTRB_int_regslice;
wire    regslice_both_src_V_strb_V_U_vld_out;
wire    regslice_both_src_V_strb_V_U_ack_in;
wire    regslice_both_src_V_user_V_U_apdone_blk;
wire   [0:0] src_TUSER_int_regslice;
wire    regslice_both_src_V_user_V_U_vld_out;
wire    regslice_both_src_V_user_V_U_ack_in;
wire    regslice_both_src_V_last_V_U_apdone_blk;
wire   [0:0] src_TLAST_int_regslice;
wire    regslice_both_src_V_last_V_U_vld_out;
wire    regslice_both_src_V_last_V_U_ack_in;
wire    regslice_both_src_V_id_V_U_apdone_blk;
wire   [0:0] src_TID_int_regslice;
wire    regslice_both_src_V_id_V_U_vld_out;
wire    regslice_both_src_V_id_V_U_ack_in;
wire    regslice_both_src_V_dest_V_U_apdone_blk;
wire   [0:0] src_TDEST_int_regslice;
wire    regslice_both_src_V_dest_V_U_vld_out;
wire    regslice_both_src_V_dest_V_U_ack_in;
wire    dst_TVALID_int_regslice;
wire    dst_TREADY_int_regslice;
wire    regslice_both_dst_V_data_V_U_vld_out;
wire    regslice_both_dst_V_keep_V_U_apdone_blk;
wire    regslice_both_dst_V_keep_V_U_ack_in_dummy;
wire    regslice_both_dst_V_keep_V_U_vld_out;
wire    regslice_both_dst_V_strb_V_U_apdone_blk;
wire    regslice_both_dst_V_strb_V_U_ack_in_dummy;
wire    regslice_both_dst_V_strb_V_U_vld_out;
wire    regslice_both_dst_V_user_V_U_apdone_blk;
wire    regslice_both_dst_V_user_V_U_ack_in_dummy;
wire    regslice_both_dst_V_user_V_U_vld_out;
wire    regslice_both_dst_V_last_V_U_apdone_blk;
wire    regslice_both_dst_V_last_V_U_ack_in_dummy;
wire    regslice_both_dst_V_last_V_U_vld_out;
wire    regslice_both_dst_V_id_V_U_apdone_blk;
wire    regslice_both_dst_V_id_V_U_ack_in_dummy;
wire    regslice_both_dst_V_id_V_U_vld_out;
wire    regslice_both_dst_V_dest_V_U_apdone_blk;
wire    regslice_both_dst_V_dest_V_U_ack_in_dummy;
wire    regslice_both_dst_V_dest_V_U_vld_out;
wire   [31:0] grp_fu_219_p00;
wire   [31:0] grp_fu_219_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start_reg = 1'b0;
end

image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start),
    .ap_done(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_done),
    .ap_idle(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_idle),
    .ap_ready(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_ready),
    .src_TVALID(src_TVALID_int_regslice),
    .dst_TREADY(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TREADY),
    .width(width_read_reg_226),
    .mul_ln112(mul_ln112_reg_286),
    .src_TDATA(src_TDATA_int_regslice),
    .src_TREADY(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_src_TREADY),
    .src_TKEEP(src_TKEEP_int_regslice),
    .src_TSTRB(src_TSTRB_int_regslice),
    .src_TUSER(src_TUSER_int_regslice),
    .src_TLAST(src_TLAST_int_regslice),
    .src_TID(src_TID_int_regslice),
    .src_TDEST(src_TDEST_int_regslice),
    .threshold_val(threshold_val_read_reg_232),
    .icmp_ln180(icmp_ln180_reg_261),
    .icmp_ln180_1(icmp_ln180_1_reg_266),
    .icmp_ln180_2(icmp_ln180_2_reg_271),
    .icmp_ln180_3(icmp_ln180_3_reg_276),
    .icmp_ln180_4(icmp_ln180_4_reg_281),
    .sub_i_i(sub_i_i_reg_256),
    .dst_TDATA(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TDATA),
    .dst_TVALID(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID),
    .dst_TKEEP(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TKEEP),
    .dst_TSTRB(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TSTRB),
    .dst_TUSER(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TUSER),
    .dst_TLAST(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TLAST),
    .dst_TID(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TID),
    .dst_TDEST(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TDEST)
);

image_pros_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .filter_select(filter_select),
    .threshold_val(threshold_val),
    .width(width),
    .height(height),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

image_pros_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_219_p0),
    .din1(grp_fu_219_p1),
    .ce(1'b1),
    .dout(grp_fu_219_p2)
);

image_pros_regslice_both #(
    .DataWidth( 8 ))
regslice_both_src_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TDATA),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_data_V_U_ack_in),
    .data_out(src_TDATA_int_regslice),
    .vld_out(src_TVALID_int_regslice),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_data_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TKEEP),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_keep_V_U_ack_in),
    .data_out(src_TKEEP_int_regslice),
    .vld_out(regslice_both_src_V_keep_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_keep_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TSTRB),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_strb_V_U_ack_in),
    .data_out(src_TSTRB_int_regslice),
    .vld_out(regslice_both_src_V_strb_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_strb_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TUSER),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_user_V_U_ack_in),
    .data_out(src_TUSER_int_regslice),
    .vld_out(regslice_both_src_V_user_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_user_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TLAST),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_last_V_U_ack_in),
    .data_out(src_TLAST_int_regslice),
    .vld_out(regslice_both_src_V_last_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_last_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TID),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_id_V_U_ack_in),
    .data_out(src_TID_int_regslice),
    .vld_out(regslice_both_src_V_id_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_id_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TDEST),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_dest_V_U_ack_in),
    .data_out(src_TDEST_int_regslice),
    .vld_out(regslice_both_src_V_dest_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_dest_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 8 ))
regslice_both_dst_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TDATA),
    .vld_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID),
    .ack_in(dst_TREADY_int_regslice),
    .data_out(dst_TDATA),
    .vld_out(regslice_both_dst_V_data_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_data_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TKEEP),
    .vld_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID),
    .ack_in(regslice_both_dst_V_keep_V_U_ack_in_dummy),
    .data_out(dst_TKEEP),
    .vld_out(regslice_both_dst_V_keep_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_keep_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TSTRB),
    .vld_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID),
    .ack_in(regslice_both_dst_V_strb_V_U_ack_in_dummy),
    .data_out(dst_TSTRB),
    .vld_out(regslice_both_dst_V_strb_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_strb_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TUSER),
    .vld_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID),
    .ack_in(regslice_both_dst_V_user_V_U_ack_in_dummy),
    .data_out(dst_TUSER),
    .vld_out(regslice_both_dst_V_user_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_user_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TLAST),
    .vld_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID),
    .ack_in(regslice_both_dst_V_last_V_U_ack_in_dummy),
    .data_out(dst_TLAST),
    .vld_out(regslice_both_dst_V_last_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_last_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TID),
    .vld_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID),
    .ack_in(regslice_both_dst_V_id_V_U_ack_in_dummy),
    .data_out(dst_TID),
    .vld_out(regslice_both_dst_V_id_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_id_V_U_apdone_blk)
);

image_pros_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TDEST),
    .vld_in(grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID),
    .ack_in(regslice_both_dst_V_dest_V_U_ack_in_dummy),
    .data_out(dst_TDEST),
    .vld_out(regslice_both_dst_V_dest_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start_reg <= 1'b1;
        end else if ((grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_ready == 1'b1)) begin
            grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        filter_select_read_reg_237 <= filter_select;
        threshold_val_read_reg_232 <= threshold_val;
        width_read_reg_226 <= width;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln180_1_reg_266 <= icmp_ln180_1_fu_195_p2;
        icmp_ln180_2_reg_271 <= icmp_ln180_2_fu_201_p2;
        icmp_ln180_3_reg_276 <= icmp_ln180_3_fu_207_p2;
        icmp_ln180_4_reg_281 <= icmp_ln180_4_fu_213_p2;
        icmp_ln180_reg_261 <= icmp_ln180_fu_189_p2;
        mul_ln112_reg_286 <= grp_fu_219_p2;
        sub_i_i_reg_256 <= sub_i_i_fu_182_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_dst_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_dst_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_dst_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        src_TREADY_int_regslice = grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_src_TREADY;
    end else begin
        src_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((regslice_both_dst_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dst_TVALID = regslice_both_dst_V_data_V_U_vld_out;

assign dst_TVALID_int_regslice = grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TVALID;

assign grp_fu_219_p0 = grp_fu_219_p00;

assign grp_fu_219_p00 = height;

assign grp_fu_219_p1 = grp_fu_219_p10;

assign grp_fu_219_p10 = width;

assign grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start = grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_ap_start_reg;

assign grp_image_pros_Pipeline_ROW_LOOP_COL_LOOP_fu_126_dst_TREADY = (dst_TREADY_int_regslice & ap_CS_fsm_state5);

assign icmp_ln180_1_fu_195_p2 = ((filter_select_read_reg_237 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln180_2_fu_201_p2 = ((filter_select_read_reg_237 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln180_3_fu_207_p2 = ((filter_select_read_reg_237 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln180_4_fu_213_p2 = ((filter_select_read_reg_237 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_189_p2 = ((filter_select_read_reg_237 == 3'd5) ? 1'b1 : 1'b0);

assign src_TREADY = regslice_both_src_V_data_V_U_ack_in;

assign sub_i_i_fu_182_p2 = ($signed(width_cast_fu_179_p1) + $signed(17'd131071));

assign width_cast_fu_179_p1 = width_read_reg_226;

endmodule //image_pros
