-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_TVALID : IN STD_LOGIC;
    dst_TREADY : IN STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    mul_ln112 : IN STD_LOGIC_VECTOR (31 downto 0);
    src_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    src_TREADY : OUT STD_LOGIC;
    src_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    threshold_val : IN STD_LOGIC_VECTOR (7 downto 0);
    icmp_ln180 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln180_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln180_2 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln180_3 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln180_4 : IN STD_LOGIC_VECTOR (0 downto 0);
    sub_i_i : IN STD_LOGIC_VECTOR (16 downto 0);
    dst_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_TVALID : OUT STD_LOGIC;
    dst_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln1027_1_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln1027_1_reg_1189 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0 : STD_LOGIC;
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0 : STD_LOGIC;
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1 : STD_LOGIC;
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0 : STD_LOGIC;
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0 : STD_LOGIC;
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal dst_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln180_1_read_reg_1164 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_1_reg_1193 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_keep_V_reg_1203 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_1208 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_user_V_reg_1213 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_V_reg_1218 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_1223 : STD_LOGIC_VECTOR (0 downto 0);
    signal image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_line_buffer_1_addr_reg_1228 : STD_LOGIC_VECTOR (9 downto 0);
    signal valid_window_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_window_reg_1239 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1035_fu_477_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1035_reg_1247 : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_pixel_last_V_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_pixel_last_V_reg_1252 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1027_fu_424_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_V_1_fu_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0357_1841_fu_158 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0357_2843_fu_162 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_fu_166 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln148_fu_491_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal row_fu_170 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1027_1_fu_416_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal indvar_flatten_fu_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1027_fu_353_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_0356840_fu_178 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0356_1842_fu_182 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_pixel_V_fu_186 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln1027_1_fu_339_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1027_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln144_fu_370_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_376_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_3_fu_392_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp55_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln144_fu_362_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_fu_455_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln144_1_fu_408_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln178_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1019_fu_482_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln_fu_554_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln840_4_fu_566_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln840_2_fu_550_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln840_fu_570_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln840_1_fu_546_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln840_5_fu_584_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln840_1_fu_588_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln88_fu_576_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln840_6_fu_594_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sum_V_5_fu_598_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln840_fu_542_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sum_V_6_fu_604_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln88_1_fu_580_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sum_V_fu_610_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln28_fu_644_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp8_fu_656_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_662_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln840_7_fu_632_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp11_fu_674_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_680_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0357839_cast_fu_628_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_0_0_0357_2843_cast_fu_652_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln840_2_fu_701_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln840_10_fu_698_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln840_11_fu_707_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal gx_V_2_fu_711_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_cast_fu_670_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln29_1_fu_636_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln840_3_fu_721_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln840_fu_717_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_V_3_fu_733_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln29_fu_688_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln840_8_fu_692_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln840_5_fu_743_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln840_1_fu_739_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_V_4_fu_749_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_V_fu_727_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_fu_761_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal abs_gx_V_fu_769_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal abs_gx_V_1_fu_775_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_V_fu_755_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_787_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal abs_gy_V_fu_795_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal abs_gy_V_1_fu_801_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln43_fu_783_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln44_fu_809_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal magnitude_V_fu_821_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_8_fu_827_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln45_1_fu_817_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln45_fu_813_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1035_1_fu_837_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln186_fu_843_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp25_fu_861_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp25_cast_fu_867_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp24_cast_fu_857_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp66_fu_871_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp7_fu_877_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln840_12_fu_885_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_0_0_0357_2843_cast36_fu_648_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln840_7_fu_889_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln840_3_fu_562_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln840_9_fu_695_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln29_fu_640_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln840_9_fu_901_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln840_13_fu_907_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0357839_cast39_fu_624_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln840_10_fu_911_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln840_14_fu_917_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln840_8_fu_895_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sum_V_4_fu_921_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_9_fu_937_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_2_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln186_fu_953_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln186_fu_530_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_fu_535_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln180_fu_965_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_616_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln178_fu_978_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1027_fu_982_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1027_fu_988_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_pixel_1_fu_957_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln180_1_fu_971_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln178_1_fu_1002_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_fu_927_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1027_fu_994_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln180_fu_1014_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_pixel_fu_849_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln178_fu_1006_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln178_fu_1026_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln180_1_fu_1031_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1027_1_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln180_2_fu_1018_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP_image_pros_stream_stream_ap_uint_ap_uinbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP_image_pros_stream_stream_ap_uint_ap_uincud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component image_pros_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_U : component image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP_image_pros_stream_stream_ap_uint_ap_uinbkb
    generic map (
        DataWidth => 8,
        AddressRange => 640,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_line_buffer_1_addr_reg_1228,
        ce0 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0,
        we0 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0,
        d0 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0,
        address1 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_address1,
        ce1 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1,
        q1 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1);

    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_U : component image_pros_image_pros_Pipeline_ROW_LOOP_COL_LOOP_image_pros_stream_stream_ap_uint_ap_uincud
    generic map (
        DataWidth => 8,
        AddressRange => 640,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_address0,
        ce0 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0,
        we0 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0,
        d0 => src_TDATA,
        q0 => image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0);

    flow_control_loop_pipe_sequential_init_U : component image_pros_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    col_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    col_fu_166 <= ap_const_lv10_0;
                elsif (((icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    col_fu_166 <= add_ln148_fu_491_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_174 <= ap_const_lv32_0;
                elsif (((icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_174 <= add_ln1027_fu_353_p2;
                end if;
            end if; 
        end if;
    end process;

    row_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    row_fu_170 <= ap_const_lv16_0;
                elsif (((icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    row_fu_170 <= select_ln1027_1_fu_416_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                current_pixel_V_fu_186 <= tmp_data_V_1_reg_1193;
                p_0_0_0356840_fu_178 <= image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1;
                p_0_0_0356_1842_fu_182 <= image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0;
                p_0_0_0357_1841_fu_158 <= p_0_0_0356_1842_fu_182;
                p_0_0_0357_2843_fu_162 <= current_pixel_V_fu_186;
                sum_V_1_fu_154 <= p_0_0_0356840_fu_178;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                dst_pixel_last_V_reg_1252 <= dst_pixel_last_V_fu_486_p2;
                image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_line_buffer_1_addr_reg_1228 <= zext_ln1027_fu_424_p1(10 - 1 downto 0);
                tmp_data_V_1_reg_1193 <= src_TDATA;
                tmp_dest_V_reg_1223 <= src_TDEST;
                tmp_id_V_reg_1218 <= src_TID;
                tmp_keep_V_reg_1203 <= src_TKEEP;
                tmp_strb_V_reg_1208 <= src_TSTRB;
                tmp_user_V_reg_1213 <= src_TUSER;
                valid_window_reg_1239 <= valid_window_fu_471_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1027_1_reg_1189 <= icmp_ln1027_1_fu_348_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln180_1_read_reg_1164 = ap_const_lv1_1))) then
                icmp_ln1035_reg_1247 <= icmp_ln1035_fu_477_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    abs_gx_V_1_fu_775_p3 <= 
        abs_gx_V_fu_769_p2 when (tmp_6_fu_761_p3(0) = '1') else 
        gx_V_fu_727_p2;
    abs_gx_V_fu_769_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gx_V_fu_727_p2));
    abs_gy_V_1_fu_801_p3 <= 
        abs_gy_V_fu_795_p2 when (tmp_7_fu_787_p3(0) = '1') else 
        gy_V_fu_755_p2;
    abs_gy_V_fu_795_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gy_V_fu_755_p2));
    add_ln1027_fu_353_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_174) + unsigned(ap_const_lv32_1));
    add_ln144_fu_370_p2 <= std_logic_vector(unsigned(row_fu_170) + unsigned(ap_const_lv16_1));
    add_ln148_fu_491_p2 <= std_logic_vector(unsigned(select_ln144_fu_362_p3) + unsigned(ap_const_lv10_1));
    add_ln186_fu_843_p2 <= std_logic_vector(unsigned(trunc_ln45_1_fu_817_p1) + unsigned(trunc_ln45_fu_813_p1));
    add_ln840_10_fu_911_p2 <= std_logic_vector(unsigned(zext_ln840_13_fu_907_p1) + unsigned(p_0_0_0357839_cast39_fu_624_p1));
    add_ln840_1_fu_588_p2 <= std_logic_vector(unsigned(zext_ln840_1_fu_546_p1) + unsigned(zext_ln840_5_fu_584_p1));
    add_ln840_2_fu_701_p2 <= std_logic_vector(unsigned(p_0_0_0357839_cast_fu_628_p1) + unsigned(p_0_0_0357_2843_cast_fu_652_p1));
    add_ln840_3_fu_721_p2 <= std_logic_vector(signed(tmp_cast_fu_670_p1) + signed(zext_ln29_1_fu_636_p1));
    add_ln840_5_fu_743_p2 <= std_logic_vector(signed(sext_ln29_fu_688_p1) + signed(zext_ln840_8_fu_692_p1));
    add_ln840_7_fu_889_p2 <= std_logic_vector(unsigned(zext_ln840_12_fu_885_p1) + unsigned(p_0_0_0357_2843_cast36_fu_648_p1));
    add_ln840_8_fu_895_p2 <= std_logic_vector(unsigned(add_ln840_7_fu_889_p2) + unsigned(zext_ln840_3_fu_562_p1));
    add_ln840_9_fu_901_p2 <= std_logic_vector(unsigned(zext_ln840_9_fu_695_p1) + unsigned(zext_ln29_fu_640_p1));
    add_ln840_fu_570_p2 <= std_logic_vector(unsigned(zext_ln840_4_fu_566_p1) + unsigned(zext_ln840_2_fu_550_p1));
    and_ln1027_1_fu_1036_p2 <= (tmp_5_fu_616_p3 and and_ln178_fu_978_p2);
    and_ln1027_fu_988_p2 <= (xor_ln1027_fu_982_p2 and and_ln178_fu_978_p2);
    and_ln178_1_fu_1002_p2 <= (valid_window_reg_1239 and icmp_ln180_3);
    and_ln178_fu_978_p2 <= (valid_window_reg_1239 and icmp_ln180_2);
    and_ln180_1_fu_1031_p2 <= (xor_ln178_fu_1026_p2 and icmp_ln180_4);
    and_ln180_fu_1014_p2 <= (valid_window_reg_1239 and icmp_ln180_4);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, src_TVALID, icmp_ln1027_1_fu_348_p2, dst_TREADY, icmp_ln1027_1_reg_1189)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (dst_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (src_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, src_TVALID, icmp_ln1027_1_fu_348_p2, dst_TREADY, icmp_ln1027_1_reg_1189, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (dst_TREADY = ap_const_logic_0)))) or ((icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (src_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, src_TVALID, icmp_ln1027_1_fu_348_p2, dst_TREADY, icmp_ln1027_1_reg_1189, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (dst_TREADY = ap_const_logic_0)))) or ((icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (src_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(src_TVALID, icmp_ln1027_1_fu_348_p2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (src_TVALID = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(dst_TREADY, icmp_ln1027_1_reg_1189)
    begin
                ap_block_state3_io <= ((icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (dst_TREADY = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(dst_TREADY, icmp_ln1027_1_reg_1189)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (dst_TREADY = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1027_1_fu_348_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln1027_1_fu_348_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    dst_TDATA <= 
        ap_const_lv8_0 when (or_ln1027_fu_1042_p2(0) = '1') else 
        select_ln180_2_fu_1018_p3;

    dst_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, dst_TREADY, icmp_ln1027_1_reg_1189, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            dst_TDATA_blk_n <= dst_TREADY;
        else 
            dst_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_TDEST <= tmp_dest_V_reg_1223;
    dst_TID <= tmp_id_V_reg_1218;
    dst_TKEEP <= tmp_keep_V_reg_1203;
    dst_TLAST <= dst_pixel_last_V_reg_1252;
    dst_TSTRB <= tmp_strb_V_reg_1208;
    dst_TUSER <= tmp_user_V_reg_1213;

    dst_TVALID_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln1027_1_reg_1189, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            dst_TVALID <= ap_const_logic_1;
        else 
            dst_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    dst_pixel_last_V_fu_486_p2 <= "1" when (sub_i_i = zext_ln1019_fu_482_p1) else "0";
    gx_V_2_fu_711_p2 <= std_logic_vector(unsigned(zext_ln840_10_fu_698_p1) - unsigned(zext_ln840_11_fu_707_p1));
    gx_V_fu_727_p2 <= std_logic_vector(unsigned(add_ln840_3_fu_721_p2) + unsigned(sext_ln840_fu_717_p1));
    gy_V_3_fu_733_p2 <= std_logic_vector(unsigned(p_0_0_0357_2843_cast_fu_652_p1) - unsigned(p_0_0_0357839_cast_fu_628_p1));
    gy_V_4_fu_749_p2 <= std_logic_vector(unsigned(add_ln840_5_fu_743_p2) + unsigned(sext_ln840_1_fu_739_p1));
    gy_V_fu_755_p2 <= std_logic_vector(unsigned(gy_V_4_fu_749_p2) - unsigned(zext_ln29_1_fu_636_p1));
    icmp55_fu_402_p2 <= "0" when (tmp_3_fu_392_p4 = ap_const_lv15_0) else "1";
    icmp_fu_386_p2 <= "0" when (tmp_2_fu_376_p4 = ap_const_lv15_0) else "1";
    icmp_ln1027_1_fu_348_p2 <= "1" when (indvar_flatten_fu_174 = mul_ln112) else "0";
    icmp_ln1027_fu_343_p2 <= "1" when (zext_ln1027_1_fu_339_p1 = width) else "0";
    icmp_ln1035_1_fu_837_p2 <= "1" when (signed(tmp_8_fu_827_p4) > signed(ap_const_lv4_0)) else "0";
    icmp_ln1035_2_fu_947_p2 <= "1" when (signed(tmp_9_fu_937_p4) > signed(ap_const_lv4_0)) else "0";
    icmp_ln1035_fu_477_p2 <= "1" when (unsigned(src_TDATA) > unsigned(threshold_val)) else "0";
    icmp_ln178_fu_465_p2 <= "0" when (tmp_4_fu_455_p4 = ap_const_lv9_0) else "1";
    icmp_ln180_1_read_reg_1164 <= icmp_ln180_1;
    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_address1 <= zext_ln1027_fu_424_p1(10 - 1 downto 0);

    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0 <= ap_const_logic_1;
        else 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1 <= ap_const_logic_1;
        else 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln1027_1_reg_1189, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_1_reg_1189 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0 <= ap_const_logic_1;
        else 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_address0 <= zext_ln1027_fu_424_p1(10 - 1 downto 0);

    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1027_1_fu_348_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0 <= ap_const_logic_1;
        else 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1027_1_fu_348_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0 <= ap_const_logic_1;
        else 
            image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    magnitude_V_fu_821_p2 <= std_logic_vector(signed(sext_ln43_fu_783_p1) + signed(sext_ln44_fu_809_p1));
    or_ln1027_fu_1042_p2 <= (and_ln180_1_fu_1031_p2 or and_ln1027_1_fu_1036_p2);
    output_pixel_1_fu_957_p3 <= 
        ap_const_lv8_FF when (icmp_ln1035_2_fu_947_p2(0) = '1') else 
        trunc_ln186_fu_953_p1;
    output_pixel_fu_849_p3 <= 
        ap_const_lv8_FF when (icmp_ln1035_1_fu_837_p2(0) = '1') else 
        add_ln186_fu_843_p2;
    p_0_0_0357839_cast39_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_V_1_fu_154),10));
    p_0_0_0357839_cast_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_V_1_fu_154),9));
    p_0_0_0357_2843_cast36_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0357_2843_fu_162),12));
    p_0_0_0357_2843_cast_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0357_2843_fu_162),9));
    select_ln1027_1_fu_416_p3 <= 
        add_ln144_fu_370_p2 when (icmp_ln1027_fu_343_p2(0) = '1') else 
        row_fu_170;
    select_ln1027_fu_994_p3 <= 
        output_pixel_1_fu_957_p3 when (and_ln1027_fu_988_p2(0) = '1') else 
        select_ln180_1_fu_971_p3;
    select_ln144_1_fu_408_p3 <= 
        icmp_fu_386_p2 when (icmp_ln1027_fu_343_p2(0) = '1') else 
        icmp55_fu_402_p2;
    select_ln144_fu_362_p3 <= 
        ap_const_lv10_0 when (icmp_ln1027_fu_343_p2(0) = '1') else 
        col_fu_166;
    select_ln178_fu_1006_p3 <= 
        trunc_ln1_fu_927_p4 when (and_ln178_1_fu_1002_p2(0) = '1') else 
        select_ln1027_fu_994_p3;
    select_ln180_1_fu_971_p3 <= 
        select_ln214_fu_535_p3 when (icmp_ln180_1(0) = '1') else 
        select_ln180_fu_965_p3;
    select_ln180_2_fu_1018_p3 <= 
        output_pixel_fu_849_p3 when (and_ln180_fu_1014_p2(0) = '1') else 
        select_ln178_fu_1006_p3;
    select_ln180_fu_965_p3 <= 
        xor_ln186_fu_530_p2 when (icmp_ln180(0) = '1') else 
        tmp_data_V_1_reg_1193;
    select_ln214_fu_535_p3 <= 
        ap_const_lv8_FF when (icmp_ln1035_reg_1247(0) = '1') else 
        ap_const_lv8_0;
        sext_ln29_fu_688_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_680_p3),11));

        sext_ln43_fu_783_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(abs_gx_V_1_fu_775_p3),12));

        sext_ln44_fu_809_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(abs_gy_V_1_fu_801_p3),12));

        sext_ln840_1_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gy_V_3_fu_733_p2),11));

        sext_ln840_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gx_V_2_fu_711_p2),11));

    shl_ln_fu_554_p3 <= (p_0_0_0356_1842_fu_182 & ap_const_lv2_0);

    src_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, src_TVALID, icmp_ln1027_1_fu_348_p2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_TDATA_blk_n <= src_TVALID;
        else 
            src_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1027_1_fu_348_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_1_fu_348_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_TREADY <= ap_const_logic_1;
        else 
            src_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    sum_V_4_fu_921_p2 <= std_logic_vector(unsigned(zext_ln840_14_fu_917_p1) + unsigned(add_ln840_8_fu_895_p2));
    sum_V_5_fu_598_p2 <= std_logic_vector(unsigned(zext_ln88_fu_576_p1) - unsigned(zext_ln840_6_fu_594_p1));
    sum_V_6_fu_604_p2 <= std_logic_vector(unsigned(sum_V_5_fu_598_p2) - unsigned(zext_ln840_fu_542_p1));
    sum_V_fu_610_p2 <= std_logic_vector(unsigned(sum_V_6_fu_604_p2) - unsigned(zext_ln88_1_fu_580_p1));
    tmp11_fu_674_p2 <= std_logic_vector(unsigned(zext_ln840_5_fu_584_p1) - unsigned(zext_ln840_7_fu_632_p1));
    tmp24_cast_fu_857_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_1_fu_588_p2),10));
    tmp25_cast_fu_867_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp25_fu_861_p2),10));
    tmp25_fu_861_p2 <= std_logic_vector(unsigned(zext_ln840_7_fu_632_p1) + unsigned(zext_ln28_fu_644_p1));
    tmp66_fu_871_p2 <= std_logic_vector(unsigned(tmp25_cast_fu_867_p1) + unsigned(tmp24_cast_fu_857_p1));
    tmp7_fu_877_p3 <= (tmp66_fu_871_p2 & ap_const_lv1_0);
    tmp8_fu_656_p2 <= std_logic_vector(unsigned(zext_ln28_fu_644_p1) - unsigned(zext_ln840_1_fu_546_p1));
    tmp_1_fu_680_p3 <= (tmp11_fu_674_p2 & ap_const_lv1_0);
    tmp_2_fu_376_p4 <= add_ln144_fu_370_p2(15 downto 1);
    tmp_3_fu_392_p4 <= row_fu_170(15 downto 1);
    tmp_4_fu_455_p4 <= select_ln144_fu_362_p3(9 downto 1);
    tmp_5_fu_616_p3 <= sum_V_fu_610_p2(11 downto 11);
    tmp_6_fu_761_p3 <= gx_V_fu_727_p2(10 downto 10);
    tmp_7_fu_787_p3 <= gy_V_fu_755_p2(10 downto 10);
    tmp_8_fu_827_p4 <= magnitude_V_fu_821_p2(11 downto 8);
    tmp_9_fu_937_p4 <= sum_V_fu_610_p2(11 downto 8);
        tmp_cast_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_662_p3),11));

    tmp_fu_662_p3 <= (tmp8_fu_656_p2 & ap_const_lv1_0);
    trunc_ln186_fu_953_p1 <= sum_V_fu_610_p2(8 - 1 downto 0);
    trunc_ln1_fu_927_p4 <= sum_V_4_fu_921_p2(11 downto 4);
    trunc_ln45_1_fu_817_p1 <= abs_gx_V_1_fu_775_p3(8 - 1 downto 0);
    trunc_ln45_fu_813_p1 <= abs_gy_V_1_fu_801_p3(8 - 1 downto 0);
    valid_window_fu_471_p2 <= (select_ln144_1_fu_408_p3 and icmp_ln178_fu_465_p2);
    xor_ln1027_fu_982_p2 <= (tmp_5_fu_616_p3 xor ap_const_lv1_1);
    xor_ln178_fu_1026_p2 <= (valid_window_reg_1239 xor ap_const_lv1_1);
    xor_ln186_fu_530_p2 <= (tmp_data_V_1_reg_1193 xor ap_const_lv8_FF);
    zext_ln1019_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln144_fu_362_p3),17));
    zext_ln1027_1_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_fu_166),16));
    zext_ln1027_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln144_fu_362_p3),64));
    zext_ln28_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0),9));
    zext_ln29_1_fu_636_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1),11));
    zext_ln29_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_1_q1),9));
    zext_ln840_10_fu_698_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_V_1_reg_1193),10));
    zext_ln840_11_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_2_fu_701_p2),10));
    zext_ln840_12_fu_885_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp7_fu_877_p3),12));
    zext_ln840_13_fu_907_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_9_fu_901_p2),10));
    zext_ln840_14_fu_917_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_10_fu_911_p2),12));
    zext_ln840_1_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0357_1841_fu_158),9));
    zext_ln840_2_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0356_1842_fu_182),11));
    zext_ln840_3_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_554_p3),12));
    zext_ln840_4_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_554_p3),11));
    zext_ln840_5_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_pixel_V_fu_186),9));
    zext_ln840_6_fu_594_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_1_fu_588_p2),12));
    zext_ln840_7_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0356840_fu_178),9));
    zext_ln840_8_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_V_1_reg_1193),11));
    zext_ln840_9_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_V_1_reg_1193),9));
    zext_ln840_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_0356840_fu_178),12));
    zext_ln88_1_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_pros_stream_stream_ap_uint_ap_uint_ap_uint_ap_uint_16_line_buffer_q0),12));
    zext_ln88_fu_576_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_fu_570_p2),12));
end behav;
